# PowerGem 插件配置

# 语言设置
# 可选值: zh (中文), en (英语), ru (俄语), es (西班牙语)
language: zh

# (已弃用) 通过指定坐标放置开启权限的机制已移除

# 随机生成的范围
random_place_range:
  world: world
  corner1:
    x: -100
    y: 160
    z: -100
  corner2:
    x: 100
    y: 30
    z: 100

# 全局开关
toggles:
  # 兑换后是否向全服广播标题
  broadcast_redeem_title: true

# 标题与特效配置
titles:
  # 集齐全部宝石后（redeemall）的展示配置
  redeem_all:
    # 是否向全服广播标题（默认继承 toggles.broadcast_redeem_title）
    broadcast: true
    # 标题文本（1-2 行）
    titles:
      - "&a%player% 集齐了全部宝石！"
      - "&e获得了至高权力！"
    # 全局音效（默认 ENTITY_ENDER_DRAGON_GROWL）
    sound: ENTITY_ENDER_DRAGON_GROWL

# 每颗宝石的自定义定义（必填）。若存在，将自动设置 required_count。
# 推荐使用“映射”形式（也兼容列表形式）
gems:
  justice:                   # 正义之石：kill 和 jail 相关
    material: RED_STAINED_GLASS
    name: "&c正义之石"
    lore:
      - "essentials.kill"
      - "essentials.jail"
      - "essentials.jail.exempt"
    redeem_title: ["&a%player% 兑换了正义之石", "&e获得正义之力！"]
    particle: FLAME
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
    permissions:
      - "essentials.kill"
      - "essentials.jail"
      - "essentials.jail.exempt"
    on_pickup:
      commands: []
      sound: ENTITY_EXPERIENCE_ORB_PICKUP
      particle: FLAME
    on_scatter:
      commands: []
      sound: ENTITY_ENDERMAN_TELEPORT
      particle: FLAME
    on_redeem:
      commands: []
      sound: UI_TOAST_CHALLENGE_COMPLETE
      particle: FIREWORK

  wealth:                    # 财富之石：money 相关
    material: GOLD_BLOCK
    name: "&6财富之石"
    lore:
      - "essentials.balance"
      - "essentials.pay"
      - "essentials.balancetop"
    redeem_title: ["&6%player% 兑换了财富之石", "&e财源滚滚来！"]
    particle: VILLAGER_HAPPY
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
    permissions:
      - "essentials.balance"
      - "essentials.pay"
      - "essentials.balancetop"
    on_pickup:
      commands: []
      sound: ENTITY_EXPERIENCE_ORB_PICKUP
      particle: VILLAGER_HAPPY
    on_scatter:
      commands: []
      sound: ENTITY_ENDERMAN_TELEPORT
      particle: VILLAGER_HAPPY
    on_redeem:
      commands: []
      sound: UI_TOAST_CHALLENGE_COMPLETE
      particle: FIREWORK

  residence:                 # 领地之石：res 权限
    material: EMERALD_BLOCK
    name: "&a领地之石"
    lore:
      - "residence.create"
      - "residence.tp"
      - "residence.list"
    redeem_title: ["&a%player% 兑换了领地之石"]
    particle: CRIT_MAGIC
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
    permissions:
      - "residence.create"
      - "residence.tp"
      - "residence.list"
    on_pickup:
      commands: []
      sound: ENTITY_EXPERIENCE_ORB_PICKUP
      particle: CRIT_MAGIC
    on_scatter:
      commands: []
      sound: ENTITY_ENDERMAN_TELEPORT
      particle: CRIT_MAGIC
    on_redeem:
      commands: []
      sound: UI_TOAST_CHALLENGE_COMPLETE
      particle: FIREWORK

# 权力强制回收（宝石位置不变)
revoke_power:
  # 权力强制回收时执行的命令
  commands:
    - "say §c%player% 的权力宝石被强制回收！"
    - "deop %player%"
  # 权力强制回收时执行的音效
  sound: ENTITY_ENDERMAN_TELEPORT
  # 权力强制回收时执行的粒子效果
  particle: FLAME

# 宝石集齐执行
gem_union_execute:
  # 宝石集齐时执行的命令
  commands:
    - "give %player% diamond 5"
    - "op %player%"
  # 宝石集齐时执行的音效
  sound: ENTITY_ENDERMAN_TELEPORT
  # 宝石集齐时执行的粒子效果
  particle: FLAME

# 宝石散落时执行
gem_scatter_execute:
  # 宝石散落时执行的命令
  commands:
    - "say 权力宝石散落了！"
    - "deop %player%"
  # 宝石散落时执行的音效
  sound: ENTITY_ENDERMAN_TELEPORT

# 授权策略
grant_policy:
  inventory_grants: false       # 背包即生效（true 开启）
  redeem_enabled: true         # 是否允许 /powergem redeem*
  full_set_grants_all: true    # 是否允许集齐后一次性生效（配合 redeemall）