# PowerGem 插件配置

required_count: 5                # 服务器宝石总数
gem_material: RED_STAINED_GLASS     # 宝石的材质，例如 STONE, DIAMOND_BLOCK, EMERALD_BLOCK, etc.
gem_name: "&c权力宝石"         # 宝石的名称，可带颜色
gem_particle: FLASH              # 宝石的粒子效果，例如 FLAME, HEART, etc.
gem_sound: AMBIENT_UNDERWATER_LOOP_ADDITIONS_ULTRA_RARE # 宝石的音效，例如 ENTITY_ENDERMAN_TELEPORT, ENTITY_EXPERIENCE_ORB_PICKUP, etc.

# 是否启用“必须在指定坐标放置”机制，如不启用则直接检查是否挨着
use_required_locations: false

# 当 use_required_locations 为 true 时，需要满足以下范围内被放置全部宝石
required_locations:
  world: world
  center:
    x: 0
    y: 70
    z: 0
  radius: 5

# 随机生成的范围
random_place_range:
  world: world
  corner1:
    x: -100
    y: 160
    z: -100
  corner2:
    x: 100
    y: 30
    z: 100

# 权力强制回收（宝石位置不变)
revoke_power:
  # 权力强制回收时执行的命令
  commands:
    - "broadcast &c%player% 的权力宝石被强制回收！"
  # 权力强制回收时执行的音效
  sound: ENTITY_ENDERMAN_TELEPORT
  # 权力强制回收时执行的粒子效果
  particle: FLAME

# 宝石集齐执行
gem_union_execute:
  # 宝石集齐时执行的命令
  commands:
    - "give %player% diamond 5"
  # 宝石集齐时执行的音效
  sound: ENTITY_ENDERMAN_TELEPORT
  # 宝石集齐时执行的粒子效果
  particle: FLAME

# 宝石散落时执行
gem_scatter_execute:
  # 宝石散落时执行的命令
  commands:
    - "broadcast &c%player% 的权力宝石散落了！"
  # 宝石散落时执行的音效
  sound: ENTITY_ENDERMAN_TELEPORT