name: PowerGem
version: 0.1
main: me.hushu.PowerGem
author: YourName
description: "一个管理 PowerGem（权力宝石）的示例插件"

# 如果你的插件需要在更高版本的 Spigot/Paper 运行，可以指定 api-version
api-version: "1.16"
commands:
  powergem:
    usage: /<command> <place|revoke|reload|powerplayer|gems|scatter|help>
    description: PowerGem plugin command
    aliases: [pg]
    permission: powergem.admin

permissions:
  powergem.admin:
    description: Allows access to all PowerGem commands
    default: op
